### ISSUE TITLE
No such file or directory when trying to init

### ISSUE THREAD

**Issue by jmuheim** [logankoester/guard-rails_best_practices#9]
```
$ guard init rails_best_practices
/Users/josh/.rvm/gems/ruby-2.0.0-p353@transition/gems/guard-2.2.5/lib/guard/plugin/base.rb:53:in `read': No such file or directory - /Users/josh/.rvm/gems/ruby-2.0.0-p353@transition/gems/guard-rails_best_practices-0.1.3/lib/guard/railsbestpractices/templates/Guardfile (Errno::ENOENT)
    from /Users/josh/.rvm/gems/ruby-2.0.0-p353@transition/gems/guard-2.2.5/lib/guard/plugin/base.rb:53:in `template'
    from /Users/josh/.rvm/gems/ruby-2.0.0-p353@transition/gems/guard-2.2.5/lib/guard/plugin_util.rb:129:in `block in add_to_guardfile'
```

**Comment by logankoester** [comment]
Can anyone confirm this with the latest `master`?

**Comment by guiceolin** [comment]
yeah i do:

```
16:37:16 - ERROR - Could not load 'guard/rails_best_practices' or '~/.guard/templates/rails_best_practices' or find class Guard::Rails_best_practices
```

using:

```
gem 'guard-rails_best_practices', git: "https://github.com/logankoester/guard-rails_best_practices.git"
```

and running:

```
$ bundle exec guard init
```

**Comment by tomoyuki28jp** [comment]
same here

**Comment by ghost** [comment]
Not only does init not work but I can't even get it to run when I manually add the code to my Guardfile:

❯ be guard
13:48:10 - ERROR - Could not load 'guard/rails_best_practices' or find class  Guard::RailsBestPractices
13:48:10 - ERROR - Invalid Guardfile, original error is: 
... 

> [#] Could not load class: "RailsBestPractices",

**Comment by delameko** [comment]
For now, reference the repo direct:

```
gem 'guard-rails_best_practices', git: 'https://github.com/logankoester/guard-rails_best_practices.git'
```

**Comment by ghost** [comment]
Using the Github repo as shown above still has the init problem for me but it does run fine after adding the Guardfile watch code.

**Comment by natesire** [comment]
I encountered similar problem

nathans-MacBook:eyehawk nathansire$ bundle exec guard init rails_best_practices
23:59:13 - ERROR - Could not load 'guard/rails_best_practices' or '~/.guard/templates/rails_best_practices' or find class Guard::Rails_best_practices

> [#]

guard :rails_best_practices do
  watch(%r{^app/(.+).rb$})
end

produces

Could not load class: "RailsBestPractices"

**Comment by tamano** [comment]
I had a same problem with the rubygems.org version, but it didn't reproduce with the master branch of github.

My Gemfile below

```
  gem 'guard-rails_best_practices', github: 'logankoester/guard-rails_best_practices'
```
